services:
  - type: web
    name: nba-dashboard
    env: python
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory contents before build:"
      ls -la
      chmod +x build.sh
      ./build.sh
      echo "Verifying final deployment structure:"
      ls -la deploy/
      ls -la deploy/data/
    startCommand: |
      echo "Starting application..."
      cd deploy
      echo "Application directory contents:"
      ls -la
      echo "Data directory contents:"
      ls -la data/
      echo "Starting Gunicorn server..."
      PYTHONPATH=/opt/render/project/src/deploy gunicorn nba_dashboard:server -b 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONPATH
        value: /opt/render/project/src/deploy 